package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.BankInfo;
import com.bdilib.smeserviceplatform.dao.EnterpriseInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface BankInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(BankInfo record);

    Integer selectfkUserIdByBankName(@Param("bankName") String bankName);

    Integer selectfkUserIdByBankNameAndBankId(@Param("bankName") String bankName,@Param("bankId") Integer bankId);

}