package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.BankInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BankInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(BankInfo record);
}