package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.EnterpriseReq;
import com.bdilib.smeserviceplatform.vo.DemandCheckVO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EnterpriseReqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    EnterpriseReq selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(EnterpriseReq record);

    List<DemandCheckVO> selectByDemandCheck(@Param("loanLimit") Integer loanLimit,@Param("rateLowerLimit")  double rateLowerLimit, @Param("rateUpperLimit")double rateUpperLimit, @Param("loanPeriod")Integer loanPeriod, @Param("guaranteeMode")Integer guaranteeMode);
    List<Integer> selectFkUserIdByDemandCheck(@Param("loanLimit") Integer loanLimit,@Param("rateLowerLimit") double rateLowerLimit, @Param("rateUpperLimit")double rateUpperLimit, @Param("loanPeriod")Integer loanPeriod, @Param("guaranteeMode")Integer guaranteeMode);

}
