package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.EnterpriseReq;

public interface EnterpriseReqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    EnterpriseReq selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(EnterpriseReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_req
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(EnterpriseReq record);
}