package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.EnterpriseCreditRate;

public interface EnterpriseCreditRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_credit_rate
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_credit_rate
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(EnterpriseCreditRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_credit_rate
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(EnterpriseCreditRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_credit_rate
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    EnterpriseCreditRate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_credit_rate
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(EnterpriseCreditRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_credit_rate
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(EnterpriseCreditRate record);
}