package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.FinancialProduct;

public interface FinancialProductMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_product
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(FinancialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_product
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(FinancialProduct record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_product
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(FinancialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_product
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(FinancialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_product
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(FinancialProduct record);
}