package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.GovernmentInfo;

public interface GovernmentInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table government_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insert(GovernmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table government_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int insertSelective(GovernmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table government_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKeySelective(GovernmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table government_info
     *
     * @mbggenerated Mon Jan 13 19:14:30 CST 2020
     */
    int updateByPrimaryKey(GovernmentInfo record);
}