package com.bdilib.smeserviceplatform.mapper;

import com.bdilib.smeserviceplatform.dao.ProductRequest;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_request
     *
     * @mbggenerated Wed Jan 15 17:40:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_request
     *
     * @mbggenerated Wed Jan 15 17:40:56 CST 2020
     */
    int insert(ProductRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_request
     *
     * @mbggenerated Wed Jan 15 17:40:56 CST 2020
     */
    int insertSelective(ProductRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_request
     *
     * @mbggenerated Wed Jan 15 17:40:56 CST 2020
     */
    ProductRequest selectByPrimaryKey(Integer id);

    List<ProductRequest> selectByFkUserId(Integer fkUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_request
     *
     * @mbggenerated Wed Jan 15 17:40:56 CST 2020
     */
    int updateByPrimaryKeySelective(ProductRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_request
     *
     * @mbggenerated Wed Jan 15 17:40:56 CST 2020
     */
    int updateByPrimaryKey(ProductRequest record);

    List<ProductRequest> selectByProductId(@Param("fkProductId") Integer fkProductId);
}